name: Docker Run test
 
on: workflow_dispatch

  #push:

    #branches: development

jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Docker Version
      run: docker -v
 
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Docker Build
      run: docker build . -t 1.0
